- hosts: localhost
  tasks:
  - name: install git
    yum: name=git state=latest
    become: yes
    become_method: sudo
  - name: clone Petclinic Repo
    git: repo=https://github.com/shimib/spring-petclinic.git dest=~/petclinic 
  - name: clone trepo Repo
    git: repo=https://github.com/shimib/trepo.git dest=~/trepo update=no
  - name: instal docker
    yum: name=docker state=latest
    become: yes
    become_method: sudo
  - name: add docker group to ec2-user
    user: name=ec2-user groups=docker append=yes
    become: yes
    become_method: sudo
  - name: start docker daemon
    service: name=docker state=started
    become: yes
    become_method: sudo
  - name: install maven
    unarchive: copy=no creates=~/apache-maven-3.3.9 dest=~ src=http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
